name: Build LaTeX document
on:
  push:
    branches:
      - main
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: main.tex
          latexmk_shell_escape: true
      - name: Prepare PDF
        run: |
          mkdir output
          mv main.pdf output/
      - name: Upload to Gihub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: output
